version = 1

[[annotations]]
path = [
  ".clang-format",
  ".python-version",
  ".vscode/c_cpp_properties.json",
  "buildspec.json",
  "CMakePresets.json",
  "scripts/windows/*.lnk",
  "scripts/windows/*.txt",
  "src/exported_symbols_linux.map",
  "src/exported_symbols_macos.txt",
  "src/exported_symbols_windows.def",
  "vcpkg-configuration.json",
  "vcpkg.json",
]
SPDX-FileCopyrightText = "2025-2026 Kaito Udagawa <umireon@kaito.tokyo>"
SPDX-License-Identifier = "CC0-1.0"
