# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Plugin CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    permissions:
      contents: read
    uses: ./.github/workflows/plugin-build-windows.yml
    with:
      environment: ${{ github.event_name == 'push' && 'production-windows' || '' }}
      pluginbinary-retention-days: 7
      VCPKG_BINARY_SOURCES: clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha}

  build-macos:
    permissions:
      contents: read
    uses: ./.github/workflows/plugin-build-macos.yml
    with:
      codesign-enabled: ${{ github.event_name == 'push' }}
      environment: ${{ github.event_name == 'push' && 'production-macos' || '' }}
      pluginbinary-retention-days: 7
      VCPKG_BINARY_SOURCES: clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha}
    secrets: inherit

  prepare-ubuntu:
    permissions:
      artifact-metadata: write
      attestations: write
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/plugin-prepare-ubuntu.yml

  build-ubuntu:
    needs: prepare-ubuntu
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/plugin-build-ubuntu.yml
    with:
      BUILDER_IMAGE_UBUNTU_X86_64: ${{ needs.prepare-ubuntu.outputs.BUILDER_IMAGE_UBUNTU_X86_64 }}
      environment: ${{ github.event_name == 'push' && 'production-ubuntu' || '' }}
      pluginbinary-retention-days: 7
      VCPKG_BINARY_SOURCES: clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha}

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: [build-windows, build-macos, build-ubuntu]
    permissions:
      artifact-metadata: write
      attestations: write
      contents: write
      issues: write
    uses: ./.github/workflows/plugin-create-release.yml
    with:
      environment: production-release
