# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Create Release

on:
  workflow_call:
    inputs:
      environment:
        description: The environment name for the build jobs
        required: true
        type: string

jobs:
  create-release:
    name: Create Release

    if: startsWith(github.ref, 'refs/tags/')

    environment: ${{ inputs.environment }}
    runs-on: ubuntu-slim

    permissions:
      artifact-metadata: write
      attestations: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Extract plugin buildspec
        id: buildspec
        uses: ./.github/actions/extract-buildspec
        with:
          path: buildspec.json

      - name: Select secure directory
        id: secure-dir
        shell: bash --noprofile --norc -euo pipefail {0}
        run: (printf artifacts= && mktemp -d -p "$RUNNER_TEMP" artifacts.XXXXXXXXXX) >> "$GITHUB_OUTPUT"

      - name: Download plugin binaries
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: ${{ steps.buildspec.outputs.name }}-pluginbinary-*
          merge-multiple: true
          path: ${{ steps.secure-dir.outputs.artifacts }}

      - name: Attest plugin binary artifacts
        id: attest
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: ${{ steps.secure-dir.outputs.artifacts }}/*

      - name: Create Draft Release
        shell: bash --noprofile --norc -euo pipefail {0}
        env:
          BUNDLE_PATH: ${{ steps.attest.outputs.bundle-path }}
          GH_TOKEN: ${{ github.token }}
        working-directory: ${{ steps.secure-dir.outputs.artifacts }}
        run: |
          shopt -s nullglob

          TAG_NAME=${GITHUB_REF#refs/tags/}

          GH_RELEASE_CREATE_ARGS=(
            --draft
            --generate-notes
            --title "$TAG_NAME"
          )

          if [[ "$TAG_NAME" =~ .*-.* ]]; then
            GH_RELEASE_CREATE_ARGS+=(--prerelease)
          fi

          gh release create "$TAG_NAME" ./* "$BUNDLE_PATH" "${GH_RELEASE_CREATE_ARGS[@]}"
